### ISSUE TITLE
1.21 Support

### ISSUE THREAD

**Issue by JustinDevB** [APDevTeam/Movecraft-Towny#5]
Plugin does not enable on latest server versions:

[13:26:03] [Server thread/INFO]: [Movecraft-Towny] Found a compatible version of Towny. Enabling Towny integration.
[13:26:03] [Server thread/ERROR]: Error occurred while enabling Movecraft-Towny v1.a.0 (Is it up to date?)
java.lang.NoSuchMethodError: 'com.palmergames.bukkit.towny.object.TownyWorld com.palmergames.bukkit.towny.db.TownyDataSource.getWorld(java.lang.String)'
	at Movecraft-Towny.jar/net.tylers1066.movecrafttowny.movecrafttowny.utils.TownyUtils.getTownyWorld(TownyUtils.java:37) ~[Movecraft-Towny.jar:?]
	at Movecraft-Towny.jar/net.tylers1066.movecrafttowny.movecrafttowny.utils.TownyUtils.getTownyConfigFromUniverse(TownyUtils.java:142) ~[Movecraft-Towny.jar:?]
	at Movecraft-Towny.jar/net.tylers1066.movecrafttowny.movecrafttowny.utils.TownyUtils.initTownyConfig(TownyUtils.java:134) ~[Movecraft-Towny.jar:?]
	at Movecraft-Towny.jar/net.tylers1066.movecrafttowny.movecrafttowny.MovecraftTowny.onEnable(MovecraftTowny.java:52) ~[Movecraft-Towny.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[purpur-1.21.1.jar:1.21.1-2300-49db849]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[purpur-1.21.1.jar:1.21.1-2300-49db849]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:654) ~[purpur-1.21.1.jar:1.21.1-2300-49db849]
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:603) ~[purpur-1.21.1.jar:1.21.1-2300-49db849]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:758) ~[purpur-1.21.1.jar:1.21.1-2300-49db849]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:520) ~[purpur-1.21.1.jar:1.21.1-2300-49db849]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:366) ~[purpur-1.21.1.jar:1.21.1-2300-49db849]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1231) ~[purpur-1.21.1.jar:1.21.1-2300-49db849]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:334) ~[purpur-1.21.1.jar:1.21.1-2300-49db849]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

**Comment by TylerS1066** [comment]
As mentioned in the readme, this plugin only supports "Towny v0.96.7.0 to 0.99.2.0 for 1.14.4 to 1.20.1".  Towny changed their API in the next version and I do not have the time to update this plugin.  However I more than welcome PRs or forks.
